import sqlite3


def create_markdown_report():
    # Connect to your working database
    conn = sqlite3.connect("compliance_tracker.db")
    cursor = conn.cursor()

    # Query the data back out of the database ordered by date
    cursor.execute(
        "SELECT title, publication_date, type, abstract FROM technical_compliance ORDER BY publication_date DESC"
    )
    records = cursor.fetchall()

    # Open a new Markdown file to write our report into
    with open("Compliance_Executive_Summary.md", "w", encoding="utf-8") as f:
        f.write("# 📋 Automated Technical Compliance & Regulatory Report\n")
        f.write(
            "This report is automatically generated by the Python data pipeline backend.\n\n"
        )
        f.write("---\n\n")

        for index, row in enumerate(records, start=1):
            title, pub_date, doc_type, abstract = row

            f.write(f"### {index}. {title}\n")
            f.write(f"* **Published On:** {pub_date} | **Type:** {doc_type}\n")
            f.write(f"* **Executive Summary:** {abstract[:200]}...\n\n")
            f.write("---\n\n")

    conn.close()
    print(
        "✨ Professional Markdown report ('Compliance_Executive_Summary.md') generated successfully!"
    )


if __name__ == "__main__":
    create_markdown_report()