# Generated by Django 6.0.6 on 2026-06-16 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicalCompliance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_number', models.CharField(max_length=100, unique=True)),
                ('title', models.TextField()),
                ('publication_date', models.DateField()),
                ('html_url', models.URLField(max_length=500)),
                ('abstract', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
