# Generated by Django 6.0.6 on 2026-06-26 01:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technicalcompliance',
            name='document_number',
        ),
        migrations.AddField(
            model_name='technicalcompliance',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
